### ISSUE TITLE
Allow for locally build images to deploy

### ISSUE THREAD

**Issue by BoukeHaarsma23** [ChimeraOS/frzr#40]
Would be nice to deploy a locally build image to remote via a simple ssh command :)

Currently doing frzr-deploy <image> will fail with some jq error.

**Comment by ruineka** [comment]
On it!

**Comment by ruineka** [comment]
Check this out https://github.com/ChimeraOS/frzr/commit/7432d5857712d89e5268b94e34abda2f5a0223dd and let me know if it works for you.

**Comment by ruineka** [comment]
> Is it maybe to possible to edit it so it can use the .img directly? That way we can skip the tarring step on local builds :)

Should be possible. I'll look into it when I get a chance.

**Comment by ruineka** [comment]
> Is it maybe to possible to edit it so it can use the .img directly? That way we can skip the tarring step on local builds :)

This has not been tested yet. https://github.com/ChimeraOS/frzr/commit/ec32551ff3c40e8eab75b9fbdd68a93b7a145891
